# Generated by Django 2.0 on 2020-05-08 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('sales', 'SALES'), ('purchase', 'PURCHASE'), ('account', 'ACCOUNT')], default='', max_length=40),
        ),
    ]
